### ISSUE TITLE
add role if permission id not in 

### ISSUE THREAD

**Issue by ldcsirtest2012** [Ferdysd96/nestjs-permission-boilerplate#6]
Hi！
  public static toCreateEntity(dto: CreateRoleRequestDto): RoleEntity {
    const entity = new RoleEntity();
    entity.name = dto.name;
    entity.permissions = Promise.resolve(dto.permissions.map((id) => new PermissionEntity({ id })));
    entity.active = true;
    return entity;
  }

When you add permissions to a role that do not exist, the permission table also increases.

**Comment by Ferdysd96** [comment]
Hello, If the id in the database does not exist, the record will not be created, the database will fail, and the id will be incremented, this happens because the primary key in the database has the type serial (auto-incrementing).

I don't see a problem with this, if I'm wrong please open issue being more specific. thanks for supporting the repository.!
